name: Fabric
version: "1.0"
mutual-tls: false

caliper:
  blockchain: fabric
  # command:
  #   start: export FABRIC_VERSION=1.4.4;export FABRIC_CA_VERSION=1.4.4;docker-compose -f networks/fabric/docker-compose/2org1peercouchdb_solo_raft/docker-compose-tls.yaml up -d;sleep 10s
  #   end: docker-compose -f networks/fabric/docker-compose/2org1peercouchdb_solo_raft/docker-compose-tls.yaml down;(test -z \"$(docker ps -aq)\") || docker rm $(docker ps -aq);(test -z \"$(docker images dev* -q)\") || docker rmi $(docker images dev* -q);rm -rf /tmp/hfc-*

info:
  Version: 1.4.7
  Size: 2 Orgs with 4 Peer
  Orderer: solo
  Distribution: Single Host
  StateDB: CouchDB

clients:
  Admin@org1.example.com:
    client:
      organization: Org1
      credentialStore:
        path: /tmp/hfc-kvs/org1
        cryptoStore:
          path: /tmp/hfc-cvs/org1
      clientPrivateKey:
        path: networks/fabric/pavan/crypto-config/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/keystore/1133171dcedbe3961f263e9018f1e9868468fdc9dea9635e8314c6ca6da4380f_sk
      clientSignedCert:
        path: networks/fabric/pavan/crypto-config/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/signcerts/User1@org1.example.com-cert.pem

  Admin@org2.example.com:
    client:
      organization: Org2
      credentialStore:
        path: /tmp/hfc-kvs/org2
        cryptoStore:
          path: /tmp/hfc-cvs/org2
      clientPrivateKey:
        path: networks/fabric/pavan/crypto-config/peerOrganizations/org2.example.com/users/User1@org2.example.com/msp/keystore/c03b6435bd25a2e4176d5dd9ffcf0310b4e94bbd762f943eca0a05bdf99f507e_sk
      clientSignedCert:
        path: networks/fabric/pavan/crypto-config/peerOrganizations/org2.example.com/users/User1@org2.example.com/msp/signcerts/User1@org2.example.com-cert.pem


channels:
  mychannel:
    # configBinary: networks/fabric/pavan/mychannel.tx
    created: true
    orderers:
    - orderer.example.com
    peers:
      peer0.org1.example.com:
        eventSource: true
      peer0.org2.example.com:
        eventSource: true

    chaincodes:
    - id: token
      version: "1.0"
      language: golang
      path: fabric/samples/token/go


organizations:
  Org1:
    mspid: Org1MSP
    peers:
    - peer0.org1.example.com
    - peer1.org1.example.com
      #certificateAuthorities:
      #- ca.org1.example.com
    adminPrivateKey:
      path: networks/fabric/pavan/crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/keystore/541ff5c2e0037c6f18909107409301ed619aa3bcd4d0d7069f13acb600e54fea_sk
    signedCert:
      path: networks/fabric/pavan/crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/signcerts/Admin@org1.example.com-cert.pem

  Org2:
    mspid: Org2MSP
    peers:
    - peer0.org2.example.com
    - peer1.org2.example.com
      #certificateAuthorities:
      #- ca.org2.example.com
    adminPrivateKey:
      path: networks/fabric/pavan/crypto-config/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp/keystore/762158d86a900978061ac7ae677263bfbaf8c926499991c4097308bb2e9b7728_sk
    signedCert:
      path: networks/fabric/pavan/crypto-config/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp/signcerts/Admin@org2.example.com-cert.pem

orderers:
  orderer.example.com:
    url: grpcs://localhost:7050
    grpcOptions:
      ssl-target-name-override: orderer.example.com
    tlsCACerts:
       path: networks/fabric/pavan/crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp/tlscacerts/tlsca.example.com-cert.pem
  # orderer2.example.com:
  #   url: grpcs://localhost:8050
  #   grpcOptions:
  #       ssl-target-name-override: orderer2.example.com
  #   tlsCACerts:
  #       path: networks/fabric/pavan/crypto-config/ordererOrganizations/example.com/orderers/orderer2.example.com/msp/tlscacerts/tlsca.example.com-cert.pem
  # orderer3.example.com:
  #     url: grpcs://localhost:9050
  #     grpcOptions:
  #         ssl-target-name-override: orderer3.example.com
  #     tlsCACerts:
  #         path: networks/fabric/pavan/crypto-config/ordererOrganizations/example.com/orderers/orderer3.example.com/msp/tlscacerts/tlsca.example.com-cert.pem

peers:
  peer0.org1.example.com:
    url: grpcs://localhost:7051
    grpcOptions:
      ssl-target-name-override: peer0.org1.example.com
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
       path: networks/fabric/pavan/crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp/tlscacerts/tlsca.org1.example.com-cert.pem

  peer1.org1.example.com:
    url: grpcs://localhost:8051
    grpcOptions:
      ssl-target-name-override: peer1.org1.example.com
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
       path: networks/fabric/pavan/crypto-config/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/msp/tlscacerts/tlsca.org1.example.com-cert.pem

  peer0.org2.example.com:
    url: grpcs://localhost:9051
    grpcOptions:
      ssl-target-name-override: peer0.org2.example.com
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
       path: networks/fabric/pavan/crypto-config/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/msp/tlscacerts/tlsca.org2.example.com-cert.pem
  peer1.org2.example.com:
    url: grpcs://localhost:10051
    grpcOptions:
      ssl-target-name-override: peer1.org2.example.com
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
       path: networks/fabric/pavan/crypto-config/peerOrganizations/org2.example.com/peers/peer1.org2.example.com/msp/tlscacerts/tlsca.org2.example.com-cert.pem

      #certificateAuthorities:
        #ca.org1.example.com:
          #url: http://localhost:7054
    #httpOptions:
   # verify: false
    #tlsCACerts:
      #  path: networks/fabric/pavan/crypto-config/peerOrganizations/org1.example.com/tlsca/tlsca.org1.example.com-cert.pem
      #registrar:
      #- enrollId: admin
      #enrollSecret: adminpw

      #ca.org2.example.com:
      #url: http://localhost:8054
      #httpOptions:
      #verify: false
    #tlsCACerts:
     #   path: networks/fabric/pavan/crypto-config/peerOrganizations/org2.example.com/tlsca/tlsca.org2.example.com-cert.pem
     #registrar:
     #- enrollId: admin
     #enrollSecret: adminpw
