version: "2"

services:
  caliper_1.4:
    container_name: caliper
    image: hyperledger/caliper:0.3.2
    command: launch master
    environment:
      - CALIPER_BIND_SUT=fabric:1.4.7
      - CALIPER_BENCHCONFIG=benchmarks/scenario/simple/pavan/config.yaml
      - CALIPER_NETWORKCONFIG=networks/fabric/pavan/network-config_1.4.yaml
    volumes:
      - ./caliper-benchmarks-local:/hyperledger/caliper/workspace
        # network_mode: host 
    network_mode: host
