version: "2"

services:
  caliper_2.1:
    container_name: caliper_2.1
    image: hyperledger/caliper:0.3.1
    command: launch master --caliper-fabric-gateway-usegateway --caliper-flow-only-test --caliper-fabric-gateway-discovery
    environment:
      - CALIPER_BIND_SUT=fabric:2.1.0
      - CALIPER_BENCHCONFIG=benchmarks/scenario/simple/pavan-v2.1/config.yaml
      - CALIPER_NETWORKCONFIG=networks/fabric/pavan-v2.1/network-config.yaml
    volumes:
      - ./caliper-benchmarks-local:/hyperledger/caliper/workspace
    network_mode: host
